export const SET_USER_REQUESTED = 'SET_USER_REQUESTED'
export const SET_USER_SUCCESSED = 'SET_USER_SUCCESSED'
export const SET_USER_FAILED = 'SET_USER_FAILED'

export const REMOVE_USER_REQUESTED = 'REMOVE_USER_REQUESTED'
export const REMOVE_USER_SUCCESSED = 'REMOVE_USER_SUCCESSED'
export const REMOVE_USER_FAILED = 'REMOVE_USER_FAILED'

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const REGISTER_REQUESTED = 'REGISTER_REQUESTED'
export const GET_USER_REQUESTED = 'GET_USER'
export const SET_USER = 'SET_USER'

export const GET_USER_LISTS_REQUESTED = 'GET_USER_LISTS_REQUESTED'
export const GET_USER_LISTS_SUCCESSED = 'GET_USER_LISTS_SUCCESSED'
export const GET_USER_LISTS_FAILED = 'GET_USER_LISTS_FAILED'

export const ADD_LIST_REQUESTED = 'ADD_LIST_REQUESTED'
export const ADD_LIST_SUCCESSED = 'ADD_LIST_SUCCESSED'
export const ADD_LIST_FAILED = 'ADD_LIST_FAILED'

export const DELETE_LIST_REQUESTED = 'DELETE_LIST_REQUESTED'
export const DELETE_LIST_SUCCESSED = 'DELETE_LIST_SUCCESSED'
export const DELETE_LIST_FAILED = 'DELETE_LIST_FAILED'

export const EDIT_LIST_REQUESTED = 'EDIT_LIST_REQUESTED'
export const EDIT_LIST_SUCCESSED = 'EDIT_LIST_SUCCESSED'
export const EDIT_LIST_FAILED = 'EDIT_LIST_FAILED'

export const GET_USER_SHARED_LISTS_REQUESTED = 'GET_USER_SHARED_LISTS_REQUESTED'
export const GET_USER_SHARED_LISTS_SUCCESSED = 'GET_USER_SHARED_LISTS_SUCCESSED'
export const GET_USER_SHARED_LISTS_FAILED = 'GET_USER_SHARED_LISTS_FAILED'

export const GET_SHARING_AVAILABLE_USERS_REQUESTED =
  'GET_SHARING_AVAILABLE_USERS_REQUESTED'
export const GET_SHARING_AVAILABLE_USERS_SUCCESSED =
  'GET_SHARING_AVAILABLE_USERS_SUCCESSED'
export const GET_SHARING_AVAILABLE_USERS_FAILED =
  'GET_SHARING_AVAILABLE_USERS_FAILED'

export const SET_SHARED_LIST_REQUESTED = 'SET_SHARED_LIST_REQUESTED'
export const SET_SHARED_LIST_SUCCESSED = 'SET_SHARED_LIST_SUCCESSED'
export const SET_SHARED_LIST_FAILED = 'SET_SHARED_LIST_FAILED'

export const SET_FILTER_REQUESTED = 'SET_FILTER_REQUESTED'
export const SET_FILTER_SUCCESSED = 'SET_FILTER_SUCCESSED'

export const GET_LIST_TODOS_REQUESTED = 'GET_LIST_TODOS_REQUESTED'
export const GET_LIST_TODOS_SUCCESSED = 'GET_LIST_TODOS_SUCCESSED'
export const GET_LIST_TODOS_FAILED = 'GET_LIST_TODOS_FAILED'

export const ADD_TODO_REQUESTED = 'ADD_TODO_REQUESTED'
export const ADD_TODO_SUCCESSED = 'ADD_TODO_SUCCESSED'
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED'

export const DELETE_TODO_REQUESTED = 'DELETE_TODO_REQUESTED'
export const DELETE_TODO_SUCCESSED = 'DELETE_TODO_SUCCESSED'
export const DELETE_TODO_FAILED = 'DELETE_TODO_FAILED'

export const EDIT_TODO_REQUESTED = 'EDIT_TODO_REQUESTED'
export const EDIT_TODO_SUCCESSED = 'EDIT_TODO_SUCCESSED'
export const EDIT_TODO_FAILED = 'EDIT_TODO_FAILED'

export const COMPLETE_TODO_REQUESTED = 'COMPLETE_TODO_REQUESTED'
export const COMPLETE_TODO_SUCCESSED = 'COMPLETE_TODO_SUCCESSED'
export const COMPLETE_TODO_FAILED = 'COMPLETE_TODO_FAILED'

export const CLEAR_COMPLETED_REQUESTED = 'CLEAR_COMPLETED_REQUESTED'
export const CLEAR_COMPLETED_SUCCESSED = 'CLEAR_COMPLETED_SUCCESSED'
export const CLEAR_COMPLETED_FAILED = 'CLEAR_COMPLETED_FAILED'

export const CHANGE_TODO_POSITION_REQUESTED = 'CHANGE_TODO_POSITION_REQUESTED'
export const CHANGE_TODO_POSITION_SUCCESSED = 'CHANGE_TODO_POSITION_SUCCESSED'
export const CHANGE_TODO_POSITION_FAILED = 'CHANGE_TODO_POSITION_FAILED'
